FROM node:18.17.0-alpine as builder
WORKDIR /app
COPY ./package.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx
ARG PORT=8080
ENV PORT=${PORT}
EXPOSE ${PORT}
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
